//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcsAcr122UScanAgent.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcsAcr122UScanAgent.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication to device fail. Please try again later..
        /// </summary>
        public static string Exception_AuthentificationToDeviceFail {
            get {
                return ResourceManager.GetString("Exception_AuthentificationToDeviceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not inserted.Please insertd cared into device and try again!.
        /// </summary>
        public static string Exception_CardNotInserted {
            get {
                return ResourceManager.GetString("Exception_CardNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader not connected.Please connect your reader and try again!.
        /// </summary>
        public static string Exception_ReaderNotConnected {
            get {
                return ResourceManager.GetString("Exception_ReaderNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong!
        ///Oops! Something went wrong!Help us improve your experience by sending an error report..
        /// </summary>
        public static string Exception_WriteToCardFail {
            get {
                return ResourceManager.GetString("Exception_WriteToCardFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelTestLocaliztion default.
        /// </summary>
        public static string LabelTestLocaliztion {
            get {
                return ResourceManager.GetString("LabelTestLocaliztion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select employee default.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test local default.
        /// </summary>
        public static string TesLocal {
            get {
                return ResourceManager.GetString("TesLocal", resourceCulture);
            }
        }
    }
}
